### ISSUE TITLE
x-calendar weird in jsfiddle

### ISSUE THREAD

**Issue by sole** [mozbrick/brick#108]
I made this inaugural jsfiddle with Brick but apparently the calendar has some cosmetic issues:

http://jsfiddle.net/29C8U/5/

https://pbs.twimg.com/media/BZ7AKC1CYAId1gV.png

**Comment by Pointy** [comment]
The day blocks are styled with "height: 100%", and the surrounding "week" is only about 1em high. The "week" div has border-box sizing and height of 2em, but it's also got some padding.

Giving the day blocks a height of 2em makes it look better, but I'm not at all qualified to claim that's the best solution.

**Comment by potch** [comment]
in this case, it's a bit of CSS that's leaking into the component:

``` css
x-flipbox div {
    padding: 0.5rem;  /* this line */
    background: #fefefe;
    text-align: center;
}
```

We could put some preventative CSS in place, but this is what Shadow DOM is supposed to fix, so I'm inclined to leave this as is for now. It's unfortunate.
