### ISSUE TITLE
<x-flipbox>'s first and last children background color

### ISSUE THREAD

**Issue by waldyrious** [mozbrick/brick#143]
In the [x-flipbox demo](http://mozilla.github.io/brick/demos/x-tag-flipbox/index.html), the background of the first and last children is set to specific colors whose meaning isn't clear from the UI. They should be mentioned in the demo page (and the custom css code should be shown there too), or otherwise be removed to reduce confusion.

``` css
x-flipbox > *:first-child{
    background-color: #fff38e;
}

x-flipbox > *:last-child{
    background-color: #9ebcc6;
}
```
