### ISSUE TITLE
Styling x-tabbar-tab

### ISSUE THREAD

**Issue by ghost** [mozbrick/brick#42]
How to style x-tabbar-tab? Neither

``` css
x-tabbar-tab {
    color: #fff;
    background: #7cc4e7;
}
```

nor 

``` css
#x-tabbar-tab-custom {
    color: #fff;
    background: #7cc4e7;
}
```

seem to work.

**Comment by ldoubleuz** [comment]
Tabbar tabs actually have a default background gradient, so you'll also need to add `background-image: none` to your `x-tabbar-tab` rules.

**Comment by ghost** [comment]
``` css
x-tabbar-tab {
    color: #fff;
    background-color: #7cc4e7;
    background-image: none;
}
```

does not make any difference!
